name: phishing
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2
  google_generative_ai: ^0.4.6
  shared_preferences: ^2.3.2
  http: ^1.2.2
  supabase_flutter: ^2.12.0
  lucide_icons: ^0.257.0
  flutter_tts: ^4.2.5
  vibration: ^3.1.7
  shimmer: ^3.0.0
  lottie: ^3.0.0
  confetti: ^0.8.0
  provider: ^6.1.1
  path_provider: ^2.1.1 
  audioplayers: ^6.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/sounds/correct.mp3
    - assets/sounds/wrong.mp3
    - assets/sounds/complete.mp3
    - assets/sounds/start.mp3
    - assets/sounds/tick.mp3
    - assets/animations/
    - assets/images/   