from app.models import QuizQuestion, QuizOption

QUESTIONS: list[QuizQuestion] = [
    QuizQuestion(
        id="q1",
        category="email",
        difficulty="easy",
        points=10,
        scenario="Recebes um e-mail do 'suporte@paypa1.com' dizendo que a tua conta foi suspensa. Pedem que cliques num link para verificar os teus dados imediatamente.",
        clue="Analisa com atenção o endereço do remetente.",
        options=[
            QuizOption(id="a", text="✅ É legítimo — vou clicar para resolver"),
            QuizOption(id="b", text="🎣 É phishing — o domínio está errado"),
        ],
        correct_option_id="b",
        explanation="O domínio 'paypa1.com' usa o número '1' em vez da letra 'l'. Esta é uma técnica clássica de typosquatting. O PayPal nunca envia e-mails de domínios alterados.",
        is_phishing=True,
    ),
    QuizQuestion(
        id="q2",
        category="email",
        difficulty="medium",
        points=20,
        scenario="Recebes um e-mail da 'Google Security <no-reply@google.com>' a avisar sobre acesso suspeito à tua conta. O e-mail tem o logótipo correto e um botão 'Verificar Atividade'.",
        clue="O domínio parece correto, mas observa o botão com atenção.",
        options=[
            QuizOption(id="a", text="✅ É legítimo — domínio Google correto"),
            QuizOption(id="b", text="🎣 É phishing — devo verificar manualmente"),
        ],
        correct_option_id="b",
        explanation="Mesmo com domínio aparentemente correto, nunca cliques em links de e-mails de segurança. Vai sempre diretamente a myaccount.google.com para verificar alertas reais.",
        is_phishing=True,
    ),
    QuizQuestion(
        id="q3",
        category="sms",
        difficulty="easy",
        points=10,
        scenario="SMS: 'BANCO DIGITAL: Sua conta foi bloqueada por segurança. Acesse agora: http://banco-digital-verificar.tk para desbloquear. Urgente!'",
        clue="Presta atenção ao domínio do link e à urgência da mensagem.",
        options=[
            QuizOption(id="a", text="✅ É legítimo — vou aceder ao link"),
            QuizOption(id="b", text="🎣 É phishing — link suspeito e urgência falsa"),
        ],
        correct_option_id="b",
        explanation="Domínios '.tk' são gratuitos e muito usados em phishing. Bancos usam sempre os seus domínios oficiais. A urgência é uma técnica de manipulação emocional.",
        is_phishing=True,
    ),
    QuizQuestion(
        id="q4",
        category="sms",
        difficulty="medium",
        points=20,
        scenario="SMS do número 40030 (número oficial da tua operadora): 'A sua fatura de Janeiro está disponível. Aceda em operadora.pt/faturas'. Nenhum link encurtado.",
        clue="Verifica o remetente e o domínio do link.",
        options=[
            QuizOption(id="a", text="✅ É legítimo — número oficial e domínio correto"),
            QuizOption(id="b", text="🎣 É phishing — desconfio de qualquer SMS"),
        ],
        correct_option_id="a",
        explanation="Este SMS tem características legítimas: número oficial da operadora, domínio correto sem subdomínios suspeitos e sem urgência. Mesmo assim, é mais seguro aceder diretamente ao site.",
        is_phishing=False,
    ),
    QuizQuestion(
        id="q5",
        category="url",
        difficulty="medium",
        points=20,
        scenario="Recebes um link: 'https://www.netflix.com.verificar-conta.xyz/login'. Tem cadeado HTTPS e o design é idêntico ao Netflix.",
        clue="O HTTPS não garante que o site é legítimo. Analisa a estrutura do URL.",
        options=[
            QuizOption(id="a", text="✅ É legítimo — tem HTTPS e parece Netflix"),
            QuizOption(id="b", text="🎣 É phishing — o domínio real é 'verificar-conta.xyz'"),
        ],
        correct_option_id="b",
        explanation="O domínio real é 'verificar-conta.xyz', não 'netflix.com'. A parte 'netflix.com' é apenas um subdomínio falso. O HTTPS apenas cifra a ligação, não garante legitimidade do site.",
        is_phishing=True,
    ),
    QuizQuestion(
        id="q6",
        category="url",
        difficulty="hard",
        points=30,
        scenario="URL recebido: 'https://accounts.google.com.login-security.net/signin/v2/identifier'. Parece o Google mas algo está errado.",
        clue="Identifica qual é o domínio principal neste URL.",
        options=[
            QuizOption(id="a", text="✅ É legítimo — começa com accounts.google.com"),
            QuizOption(id="b", text="🎣 É phishing — o domínio real é 'login-security.net'"),
        ],
        correct_option_id="b",
        explanation="O domínio real é sempre a parte antes do primeiro '/' após 'https://'. Neste caso é 'login-security.net'. 'accounts.google.com' é apenas um subdomínio dele — uma técnica avançada de engano.",
        is_phishing=True,
    ),
    QuizQuestion(
        id="q7",
        category="app",
        difficulty="easy",
        points=10,
        scenario="Encontras uma app 'WhatsApp Gold' na Google Play com 50.000 downloads prometendo funcionalidades premium gratuitas: temas, ver quem viu o teu perfil, etc.",
        clue="Aplica oficial nunca tem versões 'Gold' ou 'Premium' não oficiais.",
        options=[
            QuizOption(id="a", text="✅ É legítimo — está na Play Store oficial"),
            QuizOption(id="b", text="🎣 É maliciosa — app falsa para roubar dados"),
        ],
        correct_option_id="b",
        explanation="Apps não oficiais como 'WhatsApp Gold' são malware. Estar na Play Store não garante segurança total — apps maliciosas passam pelos filtros. Usa sempre a app oficial do desenvolvedor original.",
        is_phishing=True,
    ),
    QuizQuestion(
        id="q8",
        category="app",
        difficulty="hard",
        points=30,
        scenario="Recebes um QR code num restaurante para ver o menu. Ao escanear, pede para instalar uma 'app do menu' com permissões de acesso a contactos, SMS e localização.",
        clue="Um menu digital não precisa de permissões de SMS ou contactos.",
        options=[
            QuizOption(id="a", text="✅ É legítimo — restaurantes modernos usam apps"),
            QuizOption(id="b", text="🎣 É malicioso — permissões desnecessárias"),
        ],
        correct_option_id="b",
        explanation="Um menu digital apenas precisa de acesso à internet. Pedir acesso a SMS, contactos e localização é sinal de malware. QR codes em locais públicos podem redirecionar para sites maliciosos.",
        is_phishing=True,
    ),
    QuizQuestion(
        id="q9",
        category="email",
        difficulty="hard",
        points=30,
        scenario="E-mail da 'equipa@github.com': 'Pull request aprovado no repositório phishing-awareness. Clica para ver as alterações.' O teu nome está correto e mencionam um PR real.",
        clue="Mesmo e-mails com informação correta podem ser phishing spear.",
        options=[
            QuizOption(id="a", text="✅ É legítimo — domínio GitHub correto e contexto real"),
            QuizOption(id="b", text="🎣 Suspeito — verificar diretamente no GitHub"),
        ],
        correct_option_id="b",
        explanation="Este é spear phishing — ataque direcionado com informação real para ganhar confiança. Mesmo com domínio correto e contexto real, vai sempre diretamente ao github.com para verificar notificações.",
        is_phishing=True,
    ),
    QuizQuestion(
        id="q10",
        category="sms",
        difficulty="hard",
        points=30,
        scenario="SMS: 'Ola [nome], a tua encomenda CTT #PT123456789 está retida. Taxa aduaneira de €2.39 pendente. Paga em: ctt.pt/pagar?ref=PT123456789'",
        clue="O link parece legítimo mas verifica o domínio completo com cuidado.",
        options=[
            QuizOption(id="a", text="✅ É legítimo — domínio ctt.pt e valor baixo"),
            QuizOption(id="b", text="🎣 É phishing — verificar no site oficial CTT"),
        ],
        correct_option_id="b",
        explanation="Os CTT nunca cobram taxas aduaneiras por SMS. Este é um golpe muito comum. O valor baixo (€2.39) é propositado para parecer inofensivo. Acede sempre a ctt.pt diretamente para rastrear encomendas.",
        is_phishing=True,
    ),
]
